<a href="https://colab.research.google.com/github/nmehta32/GaussianMixtureModelling/blob/main/GMM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
mat_1 = [[9, 4, 1],
       [10, 6, 3],
       [11, 5, 2],
       [12, 7, 4]]
mat_2 = [[2, 5, 10],
       [4, 7, 11],
       [3, 6, 12],
       [5, 9, 14]]
def MeanVec(mat):
  n = 3
  temp = [0,0,0]
  mean_v = []

  for it,i in enumerate(mat):
    for it,j in enumerate(i):
      temp[it]+=j/4

  return temp
mv1 = MeanVec(mat_1)
mv2 = MeanVec(mat_2)
print('mean vector class 1',MeanVec(mat_1))


print('mean vector class 2',MeanVec(mat_2))


mean vector class 1 [10.5, 5.5, 2.5]
mean vector class 2 [3.5, 6.75, 11.75]


In [3]:
import numpy as np
def covMat(mat,mv):
  cov = []
  a = []
  for i in range(len(mat[0])):
    for j in range(len(mat)):
        a.append(mat[j][i] - mv[i])
    cov.append(a)
    a = []

  cov = np.dot(cov, np.transpose(cov))
  cov = cov/4
  return cov
cov1 = covMat(mat_1,mv1)
cov2 = covMat(mat_2,mv2)
print('COVARIANCE MATRIX FOR CLASS 1 \n',covMat(mat_1,mv1))

print('COVARIANCE MATRIX FOR CLASS 2 \n',covMat(mat_2,mv2))

COVARIANCE MATRIX FOR CLASS 1 
 [[1.25 1.   1.  ]
 [1.   1.25 1.25]
 [1.   1.25 1.25]]
COVARIANCE MATRIX FOR CLASS 2 
 [[1.25   1.625  1.375 ]
 [1.625  2.1875 1.9375]
 [1.375  1.9375 2.1875]]


In [5]:
## likelihood of observing data in a given class

def likelihood(cov,mean,data):
  det = np.linalg.det(cov)
  if det == 0:
    for i in range(len(cov)):
      for j in range(len(cov[0])):
        if i == j:
          cov[i][j] += 0.05
    det = np.linalg.det(cov)
  c1 = np.sqrt(4*det*np.pi*np.pi)
  s1 = np.subtract(np.transpose(data),np.transpose(mean))
  exp = np.exp(-0.5 * np.dot(np.dot(np.subtract(np.transpose(data),np.transpose(mean)), np.subtract(data,mean)),np.transpose(cov)))
  lh = (1/c1)*exp

  return max(lh[0])

data = [[5],[7],[12]]
l1 = likelihood(cov1,mv1,data)
l2 =  likelihood(cov2,mv2,data)
l = [l1,l2]
print('Likelyhood of class 1', likelihood(cov1,mv1,data))
print('Likelyhood of class 2', likelihood(cov2,mv2,data))
i = max(l1,l2)
print(f'Class most likely for the given data is class {l.index(i)+1}')

Likelyhood of class 1 1.3830826735200478e-44
Likelyhood of class 2 17023.48886243021
Class most likely for the given data is class 2
